name: Create and publish a Docker image

on:
  push:
    branches:
      - release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'

    - name: Set up Maven
      uses: actions/setup-java@v3
      with:
        distribution: 'maven'
        maven-version: '3.8.5'

    - name: Build with Maven
      run: mvn clean package

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: docker build -t mytodo-rear:1.0.0 .

    - name: Tag Docker image
      run: docker tag mytodo-rear:1.0.0 ${{ secrets.DOCKER_USERNAME }}/mytodo-rear:1.0.0

    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/mytodo-rear:1.0.0
